// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: party.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Certiticate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certiticate) Reset() {
	*x = Certiticate{}
	mi := &file_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certiticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certiticate) ProtoMessage() {}

func (x *Certiticate) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certiticate.ProtoReflect.Descriptor instead.
func (*Certiticate) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{0}
}

func (x *Certiticate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TaskRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tasktype      string                 `protobuf:"bytes,2,opt,name=tasktype,proto3" json:"tasktype,omitempty"`
	Status        ProcessStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=ProcessStatus" json:"status,omitempty"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRecord) Reset() {
	*x = TaskRecord{}
	mi := &file_party_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRecord) ProtoMessage() {}

func (x *TaskRecord) ProtoReflect() protoreflect.Message {
	mi := &file_party_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRecord.ProtoReflect.Descriptor instead.
func (*TaskRecord) Descriptor() ([]byte, []int) {
	return file_party_proto_rawDescGZIP(), []int{1}
}

func (x *TaskRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskRecord) GetTasktype() string {
	if x != nil {
		return x.Tasktype
	}
	return ""
}

func (x *TaskRecord) GetStatus() ProcessStatus {
	if x != nil {
		return x.Status
	}
	return ProcessStatus_PROCESS_STATUS_CREATED
}

func (x *TaskRecord) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *TaskRecord) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_party_proto protoreflect.FileDescriptor

const file_party_proto_rawDesc = "" +
	"\n" +
	"\vparty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\vconst.proto\"!\n" +
	"\vCertiticate\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8a\x01\n" +
	"\n" +
	"TaskRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\btasktype\x18\x02 \x01(\tR\btasktype\x12&\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0e.ProcessStatusR\x06status\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorBDZBgithub.com/Bridgeless-Project/tss-wrapper-svc/internal/types/typesb\x06proto3"

var (
	file_party_proto_rawDescOnce sync.Once
	file_party_proto_rawDescData []byte
)

func file_party_proto_rawDescGZIP() []byte {
	file_party_proto_rawDescOnce.Do(func() {
		file_party_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)))
	})
	return file_party_proto_rawDescData
}

var file_party_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_party_proto_goTypes = []any{
	(*Certiticate)(nil), // 0: Certiticate
	(*TaskRecord)(nil),  // 1: TaskRecord
	(ProcessStatus)(0),  // 2: ProcessStatus
}
var file_party_proto_depIdxs = []int32{
	2, // 0: TaskRecord.status:type_name -> ProcessStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_party_proto_init() }
func file_party_proto_init() {
	if File_party_proto != nil {
		return
	}
	file_const_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_party_proto_rawDesc), len(file_party_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_party_proto_goTypes,
		DependencyIndexes: file_party_proto_depIdxs,
		MessageInfos:      file_party_proto_msgTypes,
	}.Build()
	File_party_proto = out.File
	file_party_proto_goTypes = nil
	file_party_proto_depIdxs = nil
}
