// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package resources

import (
	types "github.com/Bridgeless-Project/tss-wrapper-svc/resources/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     int64                  `protobuf:"varint,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TargetTime    int64                  `protobuf:"varint,2,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeRequest) Reset() {
	*x = UpdateTimeRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeRequest) ProtoMessage() {}

func (x *UpdateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeRequest.ProtoReflect.Descriptor instead.
func (*UpdateTimeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTimeRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *UpdateTimeRequest) GetTargetTime() int64 {
	if x != nil {
		return x.TargetTime
	}
	return 0
}

type UpdateTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTimeResponse) Reset() {
	*x = UpdateTimeResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimeResponse) ProtoMessage() {}

func (x *UpdateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimeResponse.ProtoReflect.Descriptor instead.
func (*UpdateTimeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTimeResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *types.ProcessStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=ProcessStatus,oneof" json:"status,omitempty"`
	Offset        *uint64                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Limit         *uint64                `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetTasksRequest) GetStatus() types.ProcessStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return types.ProcessStatus(0)
}

func (x *GetTasksRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetTasksRequest) GetLimit() uint64 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*types.TaskRecord    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_api_proto_msgTypes[3]
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetTasksResponse) GetRecords() []*types.TaskRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*types.Certiticate   `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_api_proto_msgTypes[4]
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDataRequest) GetCertificates() []*types.Certiticate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type UpdateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        types.ProcessStatus    `protobuf:"varint,1,opt,name=status,proto3,enum=ProcessStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDataResponse) GetStatus() types.ProcessStatus {
	if x != nil {
		return x.Status
	}
	return types.ProcessStatus(0)
}

type CheckUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateNumber  string                 `protobuf:"bytes,1,opt,name=update_number,json=updateNumber,proto3" json:"update_number,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdateRequest) Reset() {
	*x = CheckUpdateRequest{}
	mi := &file_api_proto_msgTypes[6]
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateRequest) ProtoMessage() {}

func (x *CheckUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateRequest.ProtoReflect.Descriptor instead.
func (*CheckUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUpdateRequest) GetUpdateNumber() string {
	if x != nil {
		return x.UpdateNumber
	}
	return ""
}

func (x *CheckUpdateRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type CheckUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdateTime    uint64                 `protobuf:"varint,1,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	UpdateNumber  string                 `protobuf:"bytes,2,opt,name=update_number,json=updateNumber,proto3" json:"update_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpdateResponse) Reset() {
	*x = CheckUpdateResponse{}
	mi := &file_api_proto_msgTypes[7]
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpdateResponse) ProtoMessage() {}

func (x *CheckUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpdateResponse.ProtoReflect.Descriptor instead.
func (*CheckUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUpdateResponse) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *CheckUpdateResponse) GetUpdateNumber() string {
	if x != nil {
		return x.UpdateNumber
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x11types/party.proto\x1a\x11types/const.proto\"S\n" +
	"\x11UpdateTimeRequest\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vtarget_time\x18\x02 \x01(\x03R\n" +
	"targetTime\",\n" +
	"\x12UpdateTimeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\x96\x01\n" +
	"\tapi.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x11types/party.proto\x1a\x11types/const.proto\"\x96\x01\n" +
	"\x0fGetTasksRequest\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ProcessStatusH\x00R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\x04H\x01R\x06offset\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\x04H\x02R\x05limit\x88\x01\x01B\t\n" +
	"\a_statusB\t\n" +
	"\a_offsetB\b\n" +
	"\x06_limit\"9\n" +
	"\x10GetTasksResponse\x12%\n" +
	"\arecords\x18\x01 \x03(\v2\v.TaskRecordR\arecords\"E\n" +
	"\x11UpdateDataRequest\x120\n" +
	"\fcertificates\x18\x01 \x03(\v2\f.CertiticateR\fcertificates\"<\n" +
	"\x12UpdateDataResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.ProcessStatusR\x06status\"O\n" +
	"\x12CheckUpdateRequest\x12#\n" +
	"\rupdate_number\x18\x01 \x01(\tR\fupdateNumber\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\"[\n" +
	"\x13CheckUpdateResponse\x12\x1f\n" +
	"\vupdate_time\x18\x01 \x01(\x04R\n" +
	"updateTime\x12#\n" +
	"\rupdate_number\x18\x02 \x01(\tR\fupdateNumber2\xec\x01\n" +
	"\x03API\x12P\n" +
	"\vCheckUpdate\x12\x13.CheckUpdateRequest\x1a\x14.CheckUpdateResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/check/{epoch}\x12C\n" +
	"\bGetTasks\x12\x10.GetTasksRequest\x1a\x11.GetTasksResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/get_tasks\x12N\n" +
	"\n" +
	"UpdateTime\x12\x12.UpdateTimeRequest\x1a\x13.UpdateTimeResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/config/timeBZ\x92A\x1e\x12\x1c\n" +
	"\rupdate_number\x18\x02 \x01(\tR\fupdateNumber2\x98\x01\n" +
	"\x03API\x12P\n" +
	"\vCheckUpdate\x12\x13.CheckUpdateRequest\x1a\x14.CheckUpdateResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/check/{epoch}\x12?\n" +
	"\bGetTasks\x12\x10.GetTasksRequest\x1a\x11.GetTasksResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/tasksBZ\x92A\x1e\x12\x1c\n" +
	"\x13TSS-wrapper-svc API2\x050.1.0Z7github.com/Bridgeless-Project/tss-wrapper-svc/resourcesb\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_goTypes = []any{
	(*UpdateTimeRequest)(nil),   // 0: UpdateTimeRequest
	(*UpdateTimeResponse)(nil),  // 1: UpdateTimeResponse
	(*GetTasksRequest)(nil),     // 2: GetTasksRequest
	(*GetTasksResponse)(nil),    // 3: GetTasksResponse
	(*UpdateDataRequest)(nil),   // 4: UpdateDataRequest
	(*UpdateDataResponse)(nil),  // 5: UpdateDataResponse
	(*CheckUpdateRequest)(nil),  // 6: CheckUpdateRequest
	(*CheckUpdateResponse)(nil), // 7: CheckUpdateResponse
	(types.ProcessStatus)(0),    // 8: ProcessStatus
	(*types.TaskRecord)(nil),    // 9: TaskRecord
	(*types.Certiticate)(nil),   // 10: Certiticate
}
var file_api_proto_depIdxs = []int32{
	8,  // 0: GetTasksRequest.status:type_name -> ProcessStatus
	9,  // 1: GetTasksResponse.records:type_name -> TaskRecord
	10, // 2: UpdateDataRequest.certificates:type_name -> Certiticate
	8,  // 3: UpdateDataResponse.status:type_name -> ProcessStatus
	6,  // 4: API.CheckUpdate:input_type -> CheckUpdateRequest
	2,  // 5: API.GetTasks:input_type -> GetTasksRequest
	0,  // 6: API.UpdateTime:input_type -> UpdateTimeRequest
	7,  // 7: API.CheckUpdate:output_type -> CheckUpdateResponse
	3,  // 8: API.GetTasks:output_type -> GetTasksResponse
	1,  // 9: API.UpdateTime:output_type -> UpdateTimeResponse
	7,  // [7:10] is the sub-list for method output_type
	4,  // [4:7] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*GetTasksRequest)(nil),     // 0: GetTasksRequest
	(*GetTasksResponse)(nil),    // 1: GetTasksResponse
	(*UpdateDataRequest)(nil),   // 2: UpdateDataRequest
	(*UpdateDataResponse)(nil),  // 3: UpdateDataResponse
	(*CheckUpdateRequest)(nil),  // 4: CheckUpdateRequest
	(*CheckUpdateResponse)(nil), // 5: CheckUpdateResponse
	(types.ProcessStatus)(0),    // 6: ProcessStatus
	(*types.TaskRecord)(nil),    // 7: TaskRecord
	(*types.Certiticate)(nil),   // 8: Certiticate
}
var file_api_proto_depIdxs = []int32{
	6, // 0: GetTasksRequest.status:type_name -> ProcessStatus
	7, // 1: GetTasksResponse.records:type_name -> TaskRecord
	8, // 2: UpdateDataRequest.certificates:type_name -> Certiticate
	6, // 3: UpdateDataResponse.status:type_name -> ProcessStatus
	4, // 4: API.CheckUpdate:input_type -> CheckUpdateRequest
	0, // 5: API.GetTasks:input_type -> GetTasksRequest
	5, // 6: API.CheckUpdate:output_type -> CheckUpdateResponse
	1, // 7: API.GetTasks:output_type -> GetTasksResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
