// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: types/const.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_CREATED   ProcessStatus = 0
	ProcessStatus_PROCESS_STATUS_PLANNED   ProcessStatus = 1
	ProcessStatus_PROCESS_STATUS_ONGOING   ProcessStatus = 2
	ProcessStatus_PROCESS_STATUS_COMPLETED ProcessStatus = 3
	ProcessStatus_PROCESS_STATUS_FAILED    ProcessStatus = 4
	ProcessStatus_PROCESS_STATUS_RETRY     ProcessStatus = 5
)

// Enum value maps for ProcessStatus.
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_CREATED",
		1: "PROCESS_STATUS_PLANNED",
		2: "PROCESS_STATUS_ONGOING",
		3: "PROCESS_STATUS_COMPLETED",
		4: "PROCESS_STATUS_FAILED",
		5: "PROCESS_STATUS_RETRY",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_CREATED":   0,
		"PROCESS_STATUS_PLANNED":   1,
		"PROCESS_STATUS_ONGOING":   2,
		"PROCESS_STATUS_COMPLETED": 3,
		"PROCESS_STATUS_FAILED":    4,
		"PROCESS_STATUS_RETRY":     5,
	}
)

func (x ProcessStatus) Enum() *ProcessStatus {
	p := new(ProcessStatus)
	*p = x
	return p
}

func (x ProcessStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_const_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus) Type() protoreflect.EnumType {
	return &file_types_const_proto_enumTypes[0]
}

func (x ProcessStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus.Descriptor instead.
func (ProcessStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_const_proto_rawDescGZIP(), []int{0}
}

var File_types_const_proto protoreflect.FileDescriptor

const file_types_const_proto_rawDesc = "" +
	"\n" +
	"\x11types/const.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a.protoc-gen-openapiv2/options/annotations.proto*\xb6\x01\n" +
	"\rProcessStatus\x12\x1a\n" +
	"\x16PROCESS_STATUS_CREATED\x10\x00\x12\x1a\n" +
	"\x16PROCESS_STATUS_PLANNED\x10\x01\x12\x1a\n" +
	"\x16PROCESS_STATUS_ONGOING\x10\x02\x12\x1c\n" +
	"\x18PROCESS_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PROCESS_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14PROCESS_STATUS_RETRY\x10\x05B?Z=github.com/Bridgeless-Project/tss-wrapper-svc/resources/typesb\x06proto3"

var (
	file_types_const_proto_rawDescOnce sync.Once
	file_types_const_proto_rawDescData []byte
)

func file_types_const_proto_rawDescGZIP() []byte {
	file_types_const_proto_rawDescOnce.Do(func() {
		file_types_const_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_const_proto_rawDesc), len(file_types_const_proto_rawDesc)))
	})
	return file_types_const_proto_rawDescData
}

var file_types_const_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_const_proto_goTypes = []any{
	(ProcessStatus)(0), // 0: ProcessStatus
}
var file_types_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_const_proto_init() }
func file_types_const_proto_init() {
	if File_types_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_const_proto_rawDesc), len(file_types_const_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_const_proto_goTypes,
		DependencyIndexes: file_types_const_proto_depIdxs,
		EnumInfos:         file_types_const_proto_enumTypes,
	}.Build()
	File_types_const_proto = out.File
	file_types_const_proto_goTypes = nil
	file_types_const_proto_depIdxs = nil
}
