// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/const.proto

package types

// ProcessStatus represents the status of a task in the system
type ProcessStatus int32

const (
	ProcessStatus_PROCESS_STATUS_CREATED   ProcessStatus = 0
	ProcessStatus_PROCESS_STATUS_PLANNED   ProcessStatus = 1
	ProcessStatus_PROCESS_STATUS_ONGOING   ProcessStatus = 2
	ProcessStatus_PROCESS_STATUS_COMPLETED ProcessStatus = 3
	ProcessStatus_PROCESS_STATUS_FAILED    ProcessStatus = 4
	ProcessStatus_PROCESS_STATUS_RETRY     ProcessStatus = 5
)

// Enum value maps for ProcessStatus
var (
	ProcessStatus_name = map[int32]string{
		0: "PROCESS_STATUS_CREATED",
		1: "PROCESS_STATUS_PLANNED",
		2: "PROCESS_STATUS_ONGOING",
		3: "PROCESS_STATUS_COMPLETED",
		4: "PROCESS_STATUS_FAILED",
		5: "PROCESS_STATUS_RETRY",
	}
	ProcessStatus_value = map[string]int32{
		"PROCESS_STATUS_CREATED":   0,
		"PROCESS_STATUS_PLANNED":   1,
		"PROCESS_STATUS_ONGOING":   2,
		"PROCESS_STATUS_COMPLETED": 3,
		"PROCESS_STATUS_FAILED":    4,
		"PROCESS_STATUS_RETRY":     5,
	}
)

func (x ProcessStatus) String() string {
	if name, ok := ProcessStatus_name[int32(x)]; ok {
		return name
	}
	return "UNKNOWN"
}

func (x ProcessStatus) Int32() int32 {
	return int32(x)
}
